DEFAULT_PORT = 6000

# codes
# used for encrypting and decrypting messages between server and clients

DISCONNECT_REQUEST = 10
MESSAGE = 0
NAME = 2
RESPONSE = 3
DISCONNECT_CONFIRM = 11
DISCONNECT = 1
DISCONNECT_SERVER = 12
ALL_CONNECTIONS = 9
ALL_CONNECTIONS_REQUEST = 90
ALL_CONNECTIONS_SEND = 91
ALL_CONNECTIONS_CONFIRM = 92
SIMPLE = 8
MENU = 80
VOID = 81
PAUSED = 82
STOP_SERVER = 83
STOP_CLIENT = 84
COMPOUND = 4  # transfer NAME, MESSAGE/RESPONSE, RESPONSE
